package esvar.ua.workinghoursbot.domain;

public enum AuditEventType {
    USER_START,
    USER_REGISTER_SUBMITTED,
    USER_APPROVED,
    TM_PIN_SUCCESS,
    TM_PIN_FAILED,
    TM_BLOCKED,
    SCHEDULE_SUBMITTED,
    SCHEDULE_CHANGE_REQUESTED,
    SCHEDULE_EDIT_TOGGLED,
    SHIFT_CONFIRM_REQUEST_SENT,
    SHIFT_CONFIRM_YES,
    SHIFT_CONFIRM_NO,
    SHIFT_CONFIRM_AUTO_NO,
    SWAP_REQUEST_CREATED,
    SWAP_CANDIDATE_SELECTED,
    SWAP_SENT_TO_TM,
    SWAP_TM_APPROVED,
    SWAP_TM_REJECTED,
    SWAP_CANCELLED
}
