package esvar.ua.workinghoursbot.domain;

public enum TmState {
    MAIN_MENU,
    REQUESTS_LIST,
    REQUEST_DETAILS,
    LOCATIONS_MENU,
    LOCATION_ADD_INPUT,
    LOCATION_ADD_CONFIRM,
    LOCATION_DELETE_LIST,
    LOCATION_DELETE_CONFIRM,
    SCHEDULE_LOCATIONS_LIST,
    SCHEDULE_LOCATION_VIEW
}
